name: Deployment
on: [push, workflow_dispatch]
concurrency:
  group: plogon-deploy
  cancel-in-progress: true

jobs:
  run-plogon:
    name: Build Plugins
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH key
      if: github.ref == 'refs/heads/main'
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Install DalamudRepoTool
      if: github.ref == 'refs/heads/main'
      run: |
        cargo install --git https://github.com/redstrate/DalamudRepoTool.git

    - name: Checkout manifests
      uses: actions/checkout@v4
      with:
        repository: redstrate/DalamudPlugins
        path: manifests
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Checkout Plogon
      uses: actions/checkout@v4
      with:
        repository: goatcorp/Plogon
        path: Plogon

    - name: Create required folders
      run: |
        mkdir artifacts
        mkdir work
        mkdir output

    - name: Run Plogon
      working-directory: Plogon/Plogon
      run: |
        dotnet run -- \
        --manifest-folder="${{ github.workspace }}/manifests" \
        --output-folder="${{ github.workspace }}/output" \
        --work-folder="${{ github.workspace }}/work" \
        --static-folder="${{ github.workspace }}/Plogon/Plogon/static" \
        --artifact-folder="${{ github.workspace }}/artifacts" \
        --build-overrides-file="${{ github.workspace }}/manifests/overrides.toml" \
        --mode=Commit --build-all

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: plugin-artifact
        path: output

    - name: Create repo.json
      if: github.ref == 'refs/heads/main'
      run: |
        DalamudRepoTool --download-host https://dalamud.xiv.zone --repo-path output

    - name: Upload repository
      if: github.ref == 'refs/heads/main'
      run: |
        rsync -e "ssh -p 38901 -o StrictHostKeyChecking=no" --recursive output/ deploy@ryne.moe:/srv/http/dalamud

